### ISSUE TITLE
error "Unable to dump java.io.IOException: Normalization missing for: assembly_assembly_BP_25000"

### ISSUE THREAD

**Issue by HangweiXi** [aidenlab/3d-dna#101]
Hi team
I've tried to post on the google group, but I can't upload files onto it.

I'm using juicer-3ddna pipeline for hic assembly. Here is the script I used:

"export TMPDIR=/home/a1737558/hpcfs/programs/juicer/scripts/test2/tmp

/home/a1737558/hpcfs/programs/3d-dna/run-asm-pipeline.sh -r 1 \
/home/a1737558/hpcfs/vetch_polish_round2/vetch_draft_v0.1.fasta \
/home/a1737558/hpcfs/vetch_3ddna/aligned/merged_nodups.txt > 3d.log"

However, it comes with some error message:
[err.log](https://github.com/aidenlab/3d-dna/files/5794442/err.log)
Logfile attached:
[3d.log](https://github.com/aidenlab/3d-dna/files/5794444/3d.log)

I get several output files after this run, include: v0.1.0.hic, v0.1.1.hic, v0.1.polished.hic, v0.1.rawchrom.hic and v0.1.split.hic
Then I visualized those hic files in juciebox, only v0.1.0.hic make sense to me.
I'm pretty sure something wrong happened during the misjoin correction process. When I set -r 0 in the script, the error message 
"Unable to dump
java.io.IOException: Normalization missing for: assembly_assembly_BP_25000
	at juicebox.data.DatasetReaderV2.readNormalizedBlock(DatasetReaderV2.java:719)
	at juicebox.data.MatrixZoomData.dump(MatrixZoomData.java:675)
	at juicebox.tools.clt.old.Dump.dumpMatrix(Dump.java:282)
	at juicebox.tools.clt.old.Dump.run(Dump.java:505)
	at juicebox.tools.HiCTools.main(HiCTools.java:86) "
didn't appear, and the output v0.1.rawchrom.hic looks fine in juice box. When I set -r 2, those error messege appeared twice.

Can I get some advice from these questions:
1. How to fix the error occurred during the misjoin correction process?
2. The rest of the error log is consistent whether I use the misjoin correction (-r 1 or 2) or not (-r 0). Does those warning messages matter?
3. In a run with misjoin correction enabled, even if the final result is not available, v0.1.0.hic looks good in juicebox. Can I perform follow-up assembly based on v0.1.0.hic?

Thank you very much!
Hangwei

**Comment by dudcha** [comment]
Hello Hangwei,

This suggests that the code was not able to normalize your contact map at default resolution at which it typically tries to do error correction. This usually means that you have some crazy coverage issues, e.g. a large region with no data, perhaps due to contamination etc. This probably leads to no misjoin correct and the repeat annotation goes awry. Examine your .0.hic maps for coverage issues (you can load the coverage track in view, show annotation panel, basic annotations) and decide what you want to do: what are the problematic regions, if you want to filter them beforehand, if you want to keep them. If you want to run with them, you probably want to 1) change the editor-repeat-coverage and 2) change the editor-coarse-norm

Best,
Olga

**Comment by HangweiXi** [comment]
Hi Olga,

Thanks for your quick reply!
I'll move to the forum and discuss some details.
