### ISSUE TITLE
run-asm-pipeline.sh output: .FINAL.assembly, .FINAL.fasta but no .FINAL.hic output

### ISSUE THREAD

**Issue by B10inform** [aidenlab/3d-dna#106]
Hi,

run-asm-pipeline.sh gives me .FINAL.assembly, .FINAL.fasta but no .FINAL.hic output. Is it error if not which .hic should be used with .FINAL.assembly for visualization in Juicebox.

![image](https://user-images.githubusercontent.com/66449329/111220730-c7e20880-8596-11eb-9b8c-f4f3186a0f38.png)

Thanks

**Comment by dudcha** [comment]
Hello B10inform,

This is not an error: in older versions of 3D-DNA .FINAL.hic is not produced unless you pass on a special flag for gapped map. Regardless, one should not review the .FINAL. assembly in JBAT, but rather the .rawchrom.assembly (equivalent to .final.assembly in haploid mode). The reason is the inclusion of non-unique "gap scaffold" in the FINAL which has nothing to do with ordering and orientation, but rather serves to separate the linked sequences.
Olga
