### ISSUE TITLE
Divices or resource busy when scaffold

### ISSUE THREAD

**Issue by ghost** [aidenlab/3d-dna#13]
Hi
 I use 3d-dna pipline to scaffold my pre-assembly genome but the log file always report the error:`gawk: error: can't open source file `/home/lq/Storage/HiC_Analysis_Data/3d-dna-master/scaffold/scrape-mnd.awk' for reading(device or resource busy)`,but I find the script doesn't take much memory .Now the script is still running .Does it influences the final assemble ? Can I set any parameter to avoid it?I hope you can help me .Thank you !
My system is centos，and It has 40 CPUs and 128G memory ,I have 3T space for storage.The size of merged_nodups.txt  is 250G and my pre-assembly genome is 2.8G.
[Hic_Asm.log](https://github.com/theaidenlab/3d-dna/files/1917819/Hic_Asm.log)

**Comment by dudcha** [comment]
Hello FenghuJ,

This does not seem like something obviously relating to 3d-dna, and I have not seen any issues like this with other users. Notice how your log file suggests file present and then fails to find the same file just a few lines later (ren.pilon.0.cprops). Seems like some problem with system. I would definitely not trust this assembly: it keep skipping steps because files are not reachable. Maybe you are doing some weird softlinking? Spaces in some filenames that it is writing not where you expect it to be writing?.. I do not know what might be the culprit. Perhaps you can try a small subset of your problem on a different machine.

Olga

**Comment by FenghuJ** [comment]
Hello Olga,
You are right about the problem ,I access my file by the network and it's limited by the network,I use a new machine and a standalone disk , it doesn't report the error again.But I met another problem that when I run 
`awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops} | awk -f ${pipeline}/lift/lift-input-annotations-to-asm-annotations.awk ${current_cprops} <(awk '{print $2}' ${current_cprops}) - | awk -f ${pipeline}/lift/lift-asm-annotations-to-input-annotations.awk ${orig_cprops} <(awk '{print $2}' ${orig_cprops}) - > h.old.edits.txt`,
it couldn't create the file " h.old.edits.txt" and report the error:`awk: fatal: cannot open file h.old.edits.txt' for reading.`
The command is in the line 590 before you modified the pipline just now, and It's in line 673 now.I tried to copy the file it needs :ren.pilon.1.cprops and  ren.pilon.cprops and run command `awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops}` and it generated nothing ,so what's the problem ,can you give me some advice.Thank you !
[Hic_Asm.log](https://github.com/theaidenlab/3d-dna/files/1931211/Hic_Asm.log)

**Comment by dudcha** [comment]
Hello FenghuJ,

Glad you figured out your system issue. Regarding your second question, are your ren.pilon.cprops and ren.pilon.1.cprops identical?

Olga

**Comment by ghost** [comment]
Hi,Olga
      Sorry to reply later and bother you quite often ,I have found the
reason why I failed to deal the file, ren.pilon.1.cprops, because I used
the wrong shell .Now I have finish running 3d-dna and get the FINAL fasta.
Here are some question.
      I use Pacbio sequencing data for my pre-assembly and my minimum
contig length is 1512,but my FINAL.fasta contain a lot of scaffold with
length 1000.Is it correct ?I think the minimum length of scaffold should be
larger than before.
      In my log file,I get the report "not including fragment map",I
visited the forum and it seems to influence the .hic file create ? Does it
influence the fasta output?
      waiting for your reply.

2018-04-20 22:45 GMT+08:00 dudcha <notifications@github.com>:

**Comment by dudcha** [comment]
Hello FenghuJ,

Do you have access to the aidenlab forum? It really seems more like the question for that platform rather than GitHub.

Length 1000 would come from error correction: everything a mismatch gets labeled a small fraction of the contig gets excised, with the target size of 1kb by default. See Dudchenko et al., 2017 Supplement for the schematics. So their presence is expected.

3d-dna does not build fragment maps and does not need them for anything. This is normal.

Best,
Olga
