### ISSUE TITLE
run-asm-pipeline.sh: line 674: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by liufuyan2016** [aidenlab/3d-dna#16]
Ｉrun run-asm-pipeline.sh,　there is one erro :
../3d-dna-master/run-asm-pipeline.sh: line 674: syntax error near unexpected token `('
../3d-dna-master/run-asm-pipeline.sh: line 674: `		awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops} | awk -f ${pipeline}/lift/lift-input-annotations-to-asm-annotations.awk ${current_cprops} <(awk '{print $2}' ${current_cprops})- | awk -f ${pipeline}/lift/lift-asm-annotations-to-input-annotations.awk ${orig_cprops} <(awk '{print $2}' ${orig_cprops}) - > h.old.edits.txt'

Could you help me?

**Comment by dudcha** [comment]
Hi Liufuyan,

I would be happy to help however I will need some more information. What is the exact command you are running? At which round of editing is this happening? Is there a ${current_cprops} file for the round you are running (should look something like <id>.1.cprops for round 1). In addition to checking this I would suggest to load the .bed files generated by the edit pipeline and review them in Juicebox Assembly Tools (see http://aidenlab.org/assembly/manual_180322.pdf for some details): perhaps everything gets annotated as edits due to low coverage and this leads to some repercussions in reconstruction of edits which seems to be the line you are pointing out. 

Hope this helps,
Olga

**Comment by liufuyan2016** [comment]
The command below:
sh ../3d-dna-master/run-asm-pipeline.sh cd56genome.fasta /share/nas30/liufuyan/Project/HELP/Zhenjun/3-D/new/merged_nodups.txt
Thanks you for your help!

**Comment by liufuyan2016** [comment]
tree
The first round. The below is produced by the command:
.
|-- cd56genome.cprops
|-- cd56genome.fasta -> ../new/cd56genome.fasta
`-- cd56genome.mnd.txt -> /share/nas30/liufuyan/Project/HELP/Zhenjun/3-D/new/merged_nodups.txt

**Comment by dudcha** [comment]
Are these the only files produced by the pipeline? Can you give a full list of files?

Olga

**Comment by liufuyan2016** [comment]
these were the only files

**Comment by dudcha** [comment]
This means that scaffolding did not go through, not to mention editing. Are these files definitely readable? No permission problems? Was the merged nodups created with exactly this fasta file that you are using as input? E.g. if it is the same genome but contig labels are different this will not work.

Olga

**Comment by liufuyan2016** [comment]
I find the issures. The GNU bash, version 4.1.2(1) is not work. I changed the GNU bash, version 4.00 is work

**Comment by dudcha** [comment]
Great! Glad to hear. Good luck with your work,
Olga

**Comment by lurebgi** [comment]
I resolved this issue by chmod 775 run-asm-pipeline.sh, then using ./run-asm-pipeline.sh instead of sh ./run-asm-pipeline.sh
