### ISSUE TITLE
There are a lot of wrong breakpoints and Insertion sites

### ISSUE THREAD

**Issue by caixu0518** [aidenlab/3d-dna#21]
Hello 3d-dna developers, 

Automatic error correction of 3d-dna breaked many conserved genes, this step produced  a lot wrong breakpoints and Insertion sites. How can I avoid this error?

Best,
Xu

**Comment by dudcha** [comment]
Hi Xu,

Since this is not about a bug in the code, we would greatly appreciate if you could repost this on our forum instead: http://www.aidenlab.org/forum.html.

We have a few related threads on the forum concerning tuning of misjoin detector. In brief, please refer to the .wig and .bed files output by 3D-DNA. Please consider the recommendations on pages 28-29 of the Genome Assembly Cookbook for typical scenarios that require tuning as well as what the .wig and .bed tracks look like in the standard case scenario: http://aidenlab.org/assembly/manual_180322.pdf.

With best wishes,
Olga
