### ISSUE TITLE
run-asm-pipeline.sh error

### ISSUE THREAD

**Issue by Xuelei-Dai** [aidenlab/3d-dna#25]
Hi,
I run the script of run-asm-pipeline.sh,the command is `/home/software/3d-dna/run-asm-pipeline.sh /home/final.genome.new.fasta /home/merged_nodups.txt`
,but could not get result ,the error as fllows:
**awk: /home/3d-dna/utils/generate-sorted-cprops-file.awk:15: fatal: 3 is invalid as number of arguments for a
/home/3d-dna/run-asm-pipeline.sh: line 580: 1 +  / 2100000000 : syntax error: operand expected (error token 
/home/3d-dna/run-asm-pipeline.sh: line 581: [: -ne: unary operator expected
:( Cprops file not found. Please double-check your input!!
**
thanks

**Comment by dudcha** [comment]
Hi fantasticair,

Is run-asm-pipeline.sh executable? Is fasta file readable? (There is a check but just in case). Test directly the first command by running

awk -f /home/3d-dna/utils/generate-sorted-cprops-file.awk /home/final.genome.new.fasta > test.cprops

Best,
Olga

**Comment by devonorourke** [comment]
Hi @dudcha and @fantasticair ,
I received a similar error when I ran the `run-asm-pipeline.sh` script:

```
PROGMDIR=/mnt/lustre/macmaneslab/devon/pkgs/3d-dna
JUICEDIR=/mnt/lustre/macmaneslab/devon/batgenomes/assembly/juicer/LU/aligned
FASTADIR=/mnt/lustre/macmaneslab/devon/batgenomes/assembly/pilon/mylu

$PROGMDIR/run-asm-pipeline.sh $FASTADIR/LUr3p1.fasta $JUICEDIR/merged_nodups.txt
```

Initially I thought it was a permissions setting problem. So I set `chmod 700` to all three files: the script itself, the fasta file, and the text file. I then reran the program and got the exact same error. Crud.

Then I tested the fasta file to see if it would generate the `test.cprops` file as Olga suggested in the above comment and it worked perfectly. So, it didn't seem like the issue was a permissions setting, at least, not the only problem. Double crud.

I then realized that the symbolic link the program was setting up was giving me the answer:
```
lrwxrwxrwx 1 devon macmaneslab   73 Oct 22 08:48 merged_nodups.txt.mnd.txt -> /mnt/lustre/macmaneslab/devon/batgenomes/assembly/pilon/mylu/LUr3p1.fasta
-rwxr-xr-x 1 devon macmaneslab  517 Oct 22 08:48 LU3dDNA.sh
```
I was entering the **order of the fasta and text file wrong**. What I should have been entering was:
```
$PROGMDIR/run-asm-pipeline.sh $JUICEDIR/merged_nodups.txt $FASTADIR/LUr3p1.fasta 
```

_not_
```
$PROGMDIR/run-asm-pipeline.sh $FASTADIR/LUr3p1.fasta $JUICEDIR/merged_nodups.txt
```

Perhaps that was what was going in in the initial comment of this post.

Thanks to Olga and the entire team for their up to date responses - it makes troubleshooting so much easier.

**Comment by dudcha** [comment]
Hi @devonorourke,

Thanks for sharing your suggestion with this troubleshooting and for the kind words to the team. @fantasticair, I hope you were able to resolve the problem. If not, do not hesitate to reach out to try to investigate further.

Best,
Olga
