### ISSUE TITLE
Output data size of run-asm-pipeline-post-review.sh 

### ISSUE THREAD

**Issue by Xuelei-Dai** [aidenlab/3d-dna#28]
Hi,Olga
I ran the "run-asm-pipeline.sh" script and got the *.rawchrom.fasta data size of 750M, then adjusted it with juicebox and then run run-asm-pipeline-post-review.sh to get *.FINAL.fasta ，and the data size is 700M. I finally used busco to evaluate and found that its integrity dropped by 5%. I guess I ran the run-asm-pipeline-post-review.sh script and removed a lot of small fragments. If I want to keep all the fragments, how to adjust the parameters in the asm-pipeline-post-review.sh script?

Best

**Comment by dudcha** [comment]
Hi fantasticair,

haploid 3D-DNA does not filter out any sequences. When you are saying 'removed a lot of small fragments', are you referring to them not being present in the fasta? Or that a lot of misjoin correction appears to have happened and you want to tweak the misjoin detection.

You can run a script in supp/print-n50.awk to count the number of bases in both fastas - the draft and the rawchrom.fasta. It should be the same. If it is not look for error messages. If they are and what you are trying to do is tweak the parameters, since this is not a bug, check the aidenlab.org/forum.html for associated discussion.

Best,
Olga
