### ISSUE TITLE
How can I get which contigs generate one scaffold?

### ISSUE THREAD

**Issue by xinwang-bio** [aidenlab/3d-dna#32]
How can I get which contigs generate one scaffold? For example, how many contigs generate the HiC_scaffold_1 and what are the name of this contigs?  
Thanks

**Comment by dudcha** [comment]
Hi,

The .assembly file tracks changes with respect to the draft. The assembly file consists of a properties part (lines start with >) and the body (rest). Each line in the body represents a separate scaffold, and the numbers in the line are scaffold ids (see properties part) that constitute that scaffold. Minus in front of the id means reverse complement. 

I am closing this issue since this is not, in fact, an issue. Please use aidenlab.org/forum.html for general questions. We appreciate your understanding.

Olga
