### ISSUE TITLE
The tools can be used for the Triploid species ?

### ISSUE THREAD

**Issue by hzaumsq** [aidenlab/3d-dna#55]
I met a problem that my species maybe Triploid species? Did this softeware suit for it ？

**Comment by hzaumsq** [comment]
I see the 3D-dna contain the -m parameter, it just for haploid or diploid? I dont't understand the meaning of this parameter

**Comment by dudcha** [comment]
Hello hzaumsq,

You can find an example of using 3D-DNA suite for polyploid species here: https://www.nature.com/articles/s41588-019-0405-z

For information on usage consider The genome assembly cookbook, here:
https://www.dnazoo.org/methods

For questions rather than issues please consider using aidenlab.org/forum.html.

Thanks,
Olga
