### ISSUE TITLE
Specifying number of clusters/chromosomes

### ISSUE THREAD

**Issue by hdzierz** [aidenlab/3d-dna#7]
Hello,

Greetings from New Zealand. We are running your pipeline at the moment. According to your documentation, you can specify the number of expected chromosomes with -c. The latest version of your (renames) script, though, does not allow that option anymore. I am curious as to why you have removed that option. Running your pipeline at this stage resulted in 25000 super scaffolds... We wonder a bit how you can cluster without that information.

Thanks heaps in advance

Helge

**Comment by dudcha** [comment]
Hello Helge,

Apologies for the delay in answering due to travel. 3D-DNA never used the number of chromosomes to cluster: it has always performed scaffolding and error-correction genome-wide and used the number of chromosomes only when tring to better split into chromosomes. Given that in many cases the number of chromosomes is unknown we decided to remove the option while encouraging people to use an accompanying tools, Juicebox Assembly Tools (see https://www.biorxiv.org/content/early/2018/01/28/254797 and aidenlab.org/assembly), to check/tweek the output including for splitting of the megascaffold into chromosomes.

With respect to your specific problem it is somewhat hard to diagnose specifically what is going wrong for you with 25000 superscaffolds but presumably it means that the default splitter is not working for your data (possibly very low coverage or too sparse near the diagonal). Let me know if you would like me to look at the specific problem in question. Note also that the 'old' chromosome number-aware splitter is available as split_chrom_aware pipeline block.

Best,
Olga
