### ISSUE TITLE
error in run-asm-pipeline.sh

### ISSUE THREAD

**Issue by baishengjun** [aidenlab/3d-dna#79]
Hi ,
I ran 3d-dna for a plant genome with the command:
sh 3d-dna/run-asm-pipeline.sh bridged.fasta merged_nodups.txt

I got error infomation as follows:

../run-asm-pipeline.sh: line 727: syntax error near unexpected token `('
../run-asm-pipeline.sh: line 727: `             awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops} | awk -f ${pipeline}/lift/lift-input-annotations-to-asm-annotations.awk ${current_cprops} <(awk '{print $2}' ${current_cprops}) - | awk -f ${pipeline}/lift/lift-asm-annotations-to-input-annotations.awk ${orig_cprops} <(awk '{print $2}' ${orig_cprops}) - > h.old.edits.txt'

Do you know what cause this problem?
Thank you very much!

**Comment by dudcha** [comment]
Hello baishengjun,
My guess would be that you are missing some of the expected files. Look for errors earlier in the thread.
Best,
Olga

**Comment by mqding0564** [comment]
I also got the same problems. Can anybody tell us how to solve the problems.

**Comment by dudcha** [comment]
Hi,
My guess is permission issues on reading the fasta file. Please check that the compute node you are using can read the input files.
Best,
Olga

**Comment by AntetokounmJie** [comment]
> Hi,
> My guess is permission issues on reading the fasta file. Please check that the compute node you are using can read the input files.
> Best,
> Olga

Hi Olga

I also meet this error today.
After some test, i just make the run-asm-pipeline.sh be executable by "chmod u+x run-asm-pipeline.sh"
And use the command "run-asm-pipeline.sh ref.fasta merged_nodups.txt" instead of "sh run-asm-pipeline.sh ref.fasta merged_nodups.txt" to run 3d assembly.
Then the error is gone.
I am sorry about i cant find out why this thing be the cause of this error.

And the version message is below:
**version=180922
3D de novo assembly: version 180114**

Best regards.

**Comment by dudcha** [comment]
Gu Zea1nfO,

This is expected behavior. run-asm-pipeline is a bash script. I am sorry I didn't notice you had a sh in front of the command in your first post. run-asm-pipeline has #!/bin/bash as a shebang. If you make it executable, this tells the OS that bash should interpret the commands, which is exactly what happened in your case.

Best,
Olga
