### ISSUE TITLE
question about the input merged_nodups.txt

### ISSUE THREAD

**Issue by longzhangnation** [aidenlab/3d-dna#81]
HI,
  I am new to the 3D-DNA，and I have a question about the input of 3DDNA. As you write in the usage , it is OK to provide the merged_nodups.txt and draft assembly to the software , and the `run-asm-pipeline.sh` will generate a final assembly automatically . as you know , other files generated by juicer will not be used in the scaffolding ?

**Comment by dudcha** [comment]
Hi longzhangnation,

Since this is not a bug, please consider posting your question to Aidenlab.org/forum.html

For guidance on how to use the tools we’ve built in and around assembly, please consider consulting the Genome Assembly Cookbook: dnazoo.org/methods

No, other files from Juicer will not be used.

Best,
Olga
