### ISSUE TITLE
Vanilla coverage used in run-coverage-analyzer.sh

### ISSUE THREAD

**Issue by Secretloong** [aidenlab/3d-dna#96]
Hi, I have one assembly with contig N50 460KB which come from a poolling sample with ten individuals. But when I used `3d-DNA` to scaffold the genome with HiC data (37% valid_interaction/Total_pairs_processed, and 47X valid data), the scaffold N50 is only 310KB (3Mb with `SALSA2`).

I checked the `genome.nextpolish.0.hic` and `coverage_wide.at.step.0.wig`. I found there are 82% data had been identified as repeats. And there are some continuous windows with coverage larger than 60. 

I am not sure is it caused by low coverage bias with VC normalization (lead to the high coverage in some continuous windows) or just the high polymorphism (the poolling sample).

I have tested to increase the `editor_repeat_coverage`, or just edited the normalization to VC_SQRT in `run-coverage-analyzer.sh`. The result of `editor_repeat_coverage` as 8 and the result of VC_SQRT have the same contig N50 (387KB), while the fomer have scaffold N50 41MB, the later has scaffold N50 35MB (much better then `SALSA2`).

Could you suggest me which method is better? And how to determine the reason of low assembly quality with default setting (bias of normalization or high polymorphism)?

Thank you!

**Comment by dudcha** [comment]
Hi Secretloong,

Since this is not a bug, I suggest that you post this on the forum (aidnelab.org/forum.html) rather than here if you woudl like to continue the discussion. I'm going to briefly respond and close.

The standard recommendation is to load the 0.hic maps that are produced and the wig files that correspond to annotation of various problematic features such as regions that stand out due to coverage or associated with misjoins. What you are describing seems to suggest poor coverage uniformity, either because you have many alt haplotypes or because of the library or because you have a large region of very low coverage in the assembly (e.g. contaminant) that's driving your average coverage low, causing a significant chunk of your actual genome to look elevated in coverage. You'll see it all in the map/annotation, that's what they are produced for, to help interpret. Standard recommendation is to increase editor_repeat_coverage. 

Best, -Olga
